version: '3'

services:
  frontend:
    container_name: rw-frontend
    build: ./frontend
    command: serve -s build -l 3000
    restart: unless-stopped
#    ports:
#      - "3000:3000"
  api:
    container_name: rw-api
    build: ./api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_db
  auth:
    build: ./auth
    container_name: rw-auth
    command: npm run start
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - HOST=https://rw.com
      - MONGO_URL=mongodb://auth_db:27017/auth
      - API_URL=http://auth:3001/api
    depends_on:
      - auth_db
  api_db:
    container_name: rw-db
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db
  auth_db:
    container_name: rw-auth-db
    image: mongo:latest
    volumes:
      - mongodb_auth:/data/db
  nginx:
    image: nginx:stable-alpine
    container_name: rw-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
volumes:
  mongodb_api:
  mongodb_auth:
